[Config]
seed = 42
img_size = [ 256, 256,]
num_classes = 1
augment = false
upsample = false
model = "deeplabv3plus"
backbone = "p3dresnet"
backbone_weights = "/kaggle/input/d/alexisbcook/resnet50/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5"
backbone_trainable = true
dropout = false
num_epochs = 32
batch_size = 16
steps_per_update = 1
initial_learning_rate = 0.002
decay_steps = 5
decay_rate = 0.9
threshold = "auto"

[Dataset]
N_TIMES = 8
N_TIMES_BEFORE = 4
N_FRAMES = 5
N_FRAMES_BEFORE = 2
