[Config]
seed = 42
img_size = [ 256, 256,]
num_classes = 1
augment = true
upsample = false
model = "deeplabv3plus"
backbone = "p3dresnet"
backbone_weights = "imagenet"
backbone_trainable = true
dropout = true
num_epochs = 20
batch_size = 16
steps_per_update = 1
initial_learning_rate = 0.001
decay_steps = 1000
decay_rate = 0.9
threshold = "auto"

[Dataset]
N_TIMES = 8
N_TIMES_BEFORE = 4
N_FRAMES = 4
N_FRAMES_BEFORE = 3
